apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
data:
  typesense.ini: |
    [server]
    api-port = 8108
    data-dir = /data
    enable-cors = {{ .Values.typesense.enableCors }}
    {{- if .Values.typesense.extraConfig }}
    {{- toYaml .Values.typesense.extraConfig | nindent 4 }}
    {{- end }}