apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typesense.fullname" . }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.typesense.apiKey | b64enc }}
